---
# pre-commit install --allow-missing-config
# pre-commit autoupdate
# pre-commit run --all-files --color auto
exclude: |
  (?x)^(
    \.pre-commit-config\.yaml$
  )
fail_fast: true
default_stages:
  - pre-commit
default_install_hook_types:
  - commit-msg
  - pre-commit
repos:
  - repo: meta
    hooks:
      - id: identity
        name: "meta | pre-commit hooks"
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.7
    hooks:
      - id: commitizen
        name: "commitizen | validate commit messages"
        stages:
          - commit-msg
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.47.0
    hooks:
      - id: ggshield
        name: "security | scan for secrets"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        name: "git | block large files"
        args: [--maxkb=2048]
      - id: check-json
        name: "general | check JSON files"
      - id: check-toml
        name: "general | check TOML files"
      - id: end-of-file-fixer
        name: "general | fix end of file"
      - id: mixed-line-ending
        name: "general | fix line ending"
        args:
          - --fix=auto
      - id: trailing-whitespace
        name: "general | remove trailing whitespace"
      - id: pretty-format-json
        name: "general | prettify JSON files"
        args:
          - --autofix
          - --no-ensure-ascii
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        name: "md | lint: run markdownlint-cli"
        args:
          - --config
          - .config/.markdown-lint.yml
        exclude: |
          (?x)
          ^.github/instructions/.*|
          ^CHANGELOG.md|
          ^docs/legacy.*||
          ^README.md
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        name: "yaml | lint: run yamllint"
        args:
          - -c
          - .config/.yaml-lint.yml
  - repo: local
    hooks:
      - id: pin-github-action
        name: "security | gh-action: pinned sha"
        verbose: true
        files: ^\.github/workflows/[^/]+\.ya?ml$
        entry: "pin-github-action ."
        args:
          - --allow
          - "irishlab-io/*"
        language: node
        additional_dependencies:
          - pin-github-action@3.4.0
