disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "irishlab.io"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "../assets/img/website_qr.png"
  # secondaryLogo = "../assets/img/logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Simon HARVEY"
  email = "me@irishlab.io"
  # image = "img/blowfish_logo.png"
  # imageQuality = 96
  headline = "DevSecOps & Application Security"
  bio = "DevSecOps & Application Security"
  links = [
    { email = "mailto:me@irishlab.io" },
    { github = "https://github.com/irish1986" },
    { linkedin = "https://linkedin.com/in/simon-harvey-a0305029" }
  ]
