---
name: CI - PR

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

concurrency:
  group: ${{ github.ref }}-pr-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  pre-commit:
    name: Pre-Commit
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run Pre-Commit Checks
        uses: j178/prek-action@564dda4cfa5e96aafdc4a5696c4bf7b46baae5ac # v1.1.0
        env:
          SKIP: "ggshield,pin-github-action"

  secret:
    needs:
      - pre-commit
    name: Secret Scanning
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: GitGuardian scan
        id: ggshield_scan
        uses: GitGuardian/ggshield/actions/secret@edac2af7a4c4670e24600482e6ae0b3e2bb52160 # v1.45.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  build-deploy:
    needs:
      - pre-commit
      - secret
    name: GH Pages Build
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    strategy:
      matrix:
        hugo-version: ["0.152.2", "latest"]

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: ${{ matrix.hugo-version }}
          extended: true

      - name: Build
        run: |
          cd docs/
          hugo --minify
        shell: bash
